[package]

name = "cargopants"
version = "0.0.1"
authors = ["softprops <d.tangren@gmail.com>"]

[dependencies]
hyper = "*"
rustc-serialize = "0.2"
mime = "*"

[dependencies.url]
url = "https://github.com/servo/rust-url"
